server:
  port: 8191
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/zimrancis/microservices-config-store
         # search-paths:
         #  - 'service-config/*service'
         # #username: root
         # #passphrase: root
